### PR TITLE
feat: clean codebase

### PR DESCRIPTION
**Pull request by Vresod**

### CODE REVIEW

**Comment by Vresod** [comment]
featuring consistent indentation which i thought python would yell about

**Comment by rhozetta** [comment]
the bot runs, no?

if the bot runs that means the indentation is consistent that means YOU SHOULD STOP TRYING TO FIND THINGS WRONG AND DO YOUR SCHOOL WORK THAT I KNOW YOU HAVE

**Comment by Vresod** [comment]
this pr makes it more readable (by fixing the indentation and not having triple layered if statements) and also makes it run faster by not declaring all of the variables every time the user runs a command

**Comment by rhozetta** [comment]
durr im vresod, im gonna continue being a condesending asshole despite my friend being clearly pissed at me durr

**Comment by Vresod** [comment]
im trying to improve your codebase but apparently making it more readable makes the code worse? seems legit...

**Comment by rhozetta** [comment]
its the fact i told you not to that im pissed about because you seem to always think you are better than everyone

**Comment by Vresod** [comment]
its within my rights as a human to rewrite your publicly available code

**Comment by rhozetta** [comment]
1. its also within my rights as a human being to be pissed at you for doing so
2. its also within my rights as a human being to ask you politely to not (because i would be pissed if you did)
3. you once said to me, "fun fact: your code is shit and you should be ashamed to have it available on the public internet" but if its so bad why do you insist on trying to """"""""make it better""""""""

**Comment by Vresod** [comment]
uh is it stupid for me to see something i consider subpar and try to make it better?

**Pull request closed without merging**
